# Generated by Django 5.0.6 on 2024-07-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
                ('sector', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
